/*
// Even Fibbonacci number
//   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
#include <math.h>

#define     LIMIT     4 * pow(10,6)

int main(void) {
  int    f0 = 1, f1 = 2, i, sum = 0, temp;

  printf("%7s%19s%29s\n"
         "%7s%19s%29s\n"
         "%7s%19s%29s\n",
       " ", "Fibbonacci", "Even cumulative",
       "Term", "number", "total sum",
       "----", "----------", "--------------");
  printf("%7d%19d%29d\n"
         "%7d%19d%29d\n",
       1, f0, 0,
       2, f1, sum += f1);

  for (i = 3; f1 <= LIMIT; i++) {
    temp = f1;
    f1 += f0;
    f0 = temp;
    if (f1 % 2 == 0) {
      sum += f1;
      printf("%7d%19d%29d\n", i, f1, sum);
    }
  }

  return 0;
}
